### ISSUE TITLE
Reenable usage of SimdOps.assembleAndSum. Implement Panama/Native equivalent for CosineDecoder acceleration

### ISSUE THREAD

**Issue by jkni** [datastax/jvector#367]
We disabled SimdOps.assembleAndSum from PanamaVectorUtilSupport.assembleAndSum due to https://bugs.openjdk.org/browse/JDK-8321215. Now that released JDKs are fixed, we should re-test this in Bench and re-enable.

We should also implement an equivalent vector acceleration for CosineDecoder. Structurally, it's the same transformations of the PQ vector to indexes with an additional lookup table (as we need to look uppartial sums and partial magnitudes of the encoded vector).

**Comment by michaeljmarshall** [comment]
Are those gains for both sets of optimizations mentioned in the ticket?
